# Generated by Django 6.1 on 2026-08-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_invoiceitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='default_invoice_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='default_quote_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
