# Generated by Django 6.1 on 2026-08-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('public_profile_enabled', models.BooleanField(default=False)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('services', models.TextField(blank=True, help_text='Enter one service per line.')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('emergency_callouts', models.BooleanField(default=False)),
                ('show_phone_publicly', models.BooleanField(default=False)),
                ('show_email_publicly', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='core.business')),
            ],
            options={
                'verbose_name': 'Business Public Profile',
                'verbose_name_plural': 'Business Public Profiles',
                'ordering': ['business__name'],
            },
        ),
    ]
