# Generated by Django 6.1 on 2026-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspublicprofile',
            name='trade_category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('mechanical', 'Mechanical / Millwright'), ('welding', 'Welding / Fabrication'), ('hvac', 'Refrigeration / HVAC'), ('carpentry', 'Carpentry'), ('building', 'Building / Construction'), ('automotive', 'Automotive'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
