# Generated by Django 6.1 on 2026-08-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businesspublicprofile_trade_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_business_name', models.CharField(blank=True, max_length=200)),
                ('registration_type', models.CharField(choices=[('sole_proprietor', 'Sole proprietor'), ('private_company', 'Private company (Pty) Ltd'), ('close_corporation', 'Close corporation (CC)'), ('partnership', 'Partnership'), ('non_profit', 'Non-profit organisation'), ('other', 'Other')], default='private_company', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('supporting_information', models.TextField(blank=True, help_text='Provide any information that can help TradeFlow confirm the business identity and registration.')),
                ('status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected / needs information')], default='not_submitted', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Verification',
                'verbose_name_plural': 'Business Verifications',
                'ordering': ['-submitted_at', '-updated_at'],
            },
        ),
    ]
