# Generated by Django 6.1 on 2026-08-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businessreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='free', max_length=20)),
                ('billing_provider', models.CharField(choices=[('manual', 'Manual / EFT'), ('paystack', 'Paystack')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('provider_customer_code', models.CharField(blank=True, max_length=120)),
                ('provider_subscription_code', models.CharField(blank=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal TradeFlow notes about billing, manual EFT activation or account history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.business')),
            ],
            options={
                'verbose_name': 'Business Subscription',
                'verbose_name_plural': 'Business Subscriptions',
                'ordering': ['business__name'],
            },
        ),
    ]
