# Generated by Django 6.1 on 2026-08-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_businesssubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='reserved', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_category', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='core.business')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_usage_records', to='core.businesssubscription')),
            ],
            options={
                'verbose_name': 'AI Usage',
                'verbose_name_plural': 'AI Usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'period_start', 'period_end'], name='core_aiusag_busines_3ecbc3_idx'), models.Index(fields=['business', 'status', 'created_at'], name='core_aiusag_busines_9288bf_idx')],
            },
        ),
    ]
