# Generated by Django 6.1 on 2026-08-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=20)),
                ('reference', models.CharField(max_length=160, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('success', 'Successful'), ('failed', 'Failed / rejected')], default='initialized', max_length=20)),
                ('provider_transaction_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('provider_customer_code', models.CharField(blank=True, max_length=120)),
                ('provider_subscription_code', models.CharField(blank=True, max_length=120)),
                ('last_event_type', models.CharField(blank=True, max_length=80)),
                ('provider_message', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='core.business')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.businesssubscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
