# Generated by Django 6.1 on 2026-08-29 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_subscriptionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EFTSubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('customer_payment_reference', models.CharField(blank=True, help_text='Reference supplied by the customer after making the EFT payment.', max_length=160)),
                ('customer_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending_review', 'Pending verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='awaiting_payment', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eft_subscription_requests', to='core.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_eft_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eft_requests', to='core.businesssubscription')),
            ],
            options={
                'verbose_name': 'EFT Subscription Request',
                'verbose_name_plural': 'EFT Subscription Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
